# Generated by Django 3.2.6 on 2021-08-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
